name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env: 
  DBUSER: ${{ secrets.DBUSER }}
  DBPASSWORD: ${{ secrets.DBPASSWORD }}
  DBNAME: "test"
  DBURL: ${{ secrets.DBURL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build docker containers
        run: docker-compose build 
      
      - name: run docker containers
        run: docker-compose up -d
      
      - name: run npm install
        run: |
          cd images/api
          npm ci
          
      - name: run tests
        run: |
          cd images/api
          npm run test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker-compose build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: publish
        run: docker-compose push
